import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar/navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<link
				rel="icon"
				href="https://logos-world.net/wp-content/uploads/2023/12/F1-Logo.png"
			/>
			<body className={poppins.className}>
				<Navbar />
				<Toaster />
				{children}
				<Footer />
			</body>
		</html>
	);
}
